package tests;

import base.BaseTest;
import config.ConfigReader;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import pages.AddProductPage;
import pages.AdminLoginPage;

/**
 * AddProductTest.java
 *
 * Covers Module 4 (Add Product): smoke checks, every dropdown option,
 * field-level boundary/negative values, the Description/Pricing/
 * Categories/Search Engines tabs, and Save & Reload.
 *
 * Three tests in this class are EXPECTED TO FAIL on purpose - they
 * assert the correct, sensible behaviour (negative price/stock should
 * be rejected, a duplicate product code should be rejected) and the
 * live CubeCart site does not do that. Each one is marked
 * "KNOWN APPLICATION BUG" with the real behaviour that was observed,
 * confirmed by hand before being written here. These are not broken
 * assertions - they document genuine defects in the application.
 *
 * NOTE: This version of CubeCart's Add Product form only has "Save"
 * and "Save & Reload" buttons - there is no Cancel or Reset button, so
 * those two scenarios from the brief do not apply to this application
 * and are not faked here.
 */
public class AddProductTest extends BaseTest {

    private AddProductPage addProductPage;

    @BeforeMethod(dependsOnMethods = "setUp")
    public void loginAsAdminAndOpenAddProduct() {
        openAdminUrl();
        new AdminLoginPage(driver).login(ConfigReader.getAdminUsername(), ConfigReader.getAdminPassword());

        addProductPage = new AddProductPage(driver);
        addProductPage.navigateToAddProductPage();
    }

    // ===================== SMOKE TESTS =====================

    @Test(priority = 1)
    public void testAddProductPageLoads() {
        Assert.assertTrue(addProductPage.isAddProductPageDisplayed(), "Add Product page did not load.");
    }

    @Test(priority = 2)
    public void testAddProductWithValidDetails() {
        long uniqueNumber = System.currentTimeMillis();

        addProductPage.addProductWithFullDetails(
                "Automation Test Product " + uniqueNumber, "AUTO" + uniqueNumber, "Samsung", "New",
                "1.5", "50", "Full description generated by Selenium automation.",
                "Short description for automation test.", "999", "Automation Test Product");

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product was not saved successfully with valid details.");
    }

    @Test(priority = 3)
    public void testAddProductWithoutProductName() {
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductNameValidationErrorDisplayed(),
                "Product should not save successfully without a Product Name.");
        Assert.assertFalse(addProductPage.isProductSavedSuccessfully(),
                "No success message should be shown when Product Name is missing.");
    }

    // ===================== MANUFACTURER / CONDITION / DIMENSION DROPDOWNS =====================

    @DataProvider(name = "manufacturerOptions")
    public Object[][] manufacturerOptions() {
        return new Object[][]{
                {"Google"}, {"Motorola"}, {"One plus"}, {"Redmi"}, {"Samsung"}, {"sony"}, {"Vivo"},
        };
    }

    @Test(dataProvider = "manufacturerOptions", priority = 4)
    public void testAddProductWithEachManufacturer(String manufacturer) {
        addProductPage.enterProductName("Manufacturer Test " + manufacturer + " " + System.currentTimeMillis());
        addProductPage.selectManufacturer(manufacturer);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with manufacturer '" + manufacturer + "'.");
    }

    @DataProvider(name = "conditionOptions")
    public Object[][] conditionOptions() {
        return new Object[][]{
                {"New"}, {"Used"}, {"Refurbished"}, {"Damaged"},
        };
    }

    @Test(dataProvider = "conditionOptions", priority = 4)
    public void testAddProductWithEachCondition(String condition) {
        addProductPage.enterProductName("Condition Test " + condition + " " + System.currentTimeMillis());
        addProductPage.selectCondition(condition);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with condition '" + condition + "'.");
    }

    @DataProvider(name = "dimensionUnitOptions")
    public Object[][] dimensionUnitOptions() {
        return new Object[][]{
                {"Centimeters (cm)"}, {"Inches (in)"},
        };
    }

    @Test(dataProvider = "dimensionUnitOptions", priority = 4)
    public void testAddProductWithEachDimensionUnit(String dimensionUnit) {
        addProductPage.enterProductName("Dimension Unit Test " + System.currentTimeMillis());
        addProductPage.selectDimensionUnit(dimensionUnit);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with dimension unit '" + dimensionUnit + "'.");
    }

    // ===================== GENERAL TAB: BOUNDARY / SPECIAL INPUT =====================

    @DataProvider(name = "generalFieldScenarios")
    public Object[][] generalFieldScenarios() {
        return new Object[][]{
                {"TC_EmptyProductCode_StillSucceeds", "General Field Test", ""},
                {"TC_SpecialCharactersInProductName", "Product @#$% Special!", "SPEC" + System.nanoTime()},
                {"TC_NumericProductName", "12345", "NUM" + System.nanoTime()},
                {"TC_LeadingTrailingSpacesInProductName", "   Padded Product Name   ", "PAD" + System.nanoTime()},
                {"TC_VeryLongProductName", "A".repeat(300), "LONG" + System.nanoTime()},
                {"TC_SpecialCharactersInProductCode", "Special Code Product", "CODE-#" + System.nanoTime()},
                {"TC_MinLengthProductName", "A", "MIN" + System.nanoTime()},
        };
    }

    @Test(dataProvider = "generalFieldScenarios", priority = 5)
    public void testAddProductGeneralFieldScenarios(String testCaseId, String productName, String productCode) {
        addProductPage.enterProductName(productName + " " + System.currentTimeMillis());
        addProductPage.enterProductCode(productCode);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                testCaseId + ": expected the product to save successfully.");
    }

    // ===================== PRICING TAB =====================

    @DataProvider(name = "validPricingScenarios")
    public Object[][] validPricingScenarios() {
        return new Object[][]{
                {"TC_ZeroPrice", "0"},
                {"TC_DecimalPrice", "99.99"},
                {"TC_LargePrice", "999999999"},
        };
    }

    @Test(dataProvider = "validPricingScenarios", priority = 6)
    public void testAddProductWithValidPricing(String testCaseId, String price) {
        addProductPage.enterProductName("Pricing Test " + testCaseId + " " + System.currentTimeMillis());
        addProductPage.openPricingTab();
        addProductPage.enterRetailPrice(price);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                testCaseId + ": expected the product to save successfully with price " + price + ".");
    }

    /**
     * KNOWN APPLICATION BUG: the Retail Price field accepts a negative
     * value (e.g. -500) and saves the product with no validation error at
     * all - confirmed live, the product list then shows a price of
     * "-500.00". A real store must never allow a negative selling price.
     * Expected: the form should reject a negative price.
     * Actual: the product is saved with the negative price stored as-is.
     */
    @Test(priority = 6)
    public void testAddProductWithNegativePriceShouldBeRejected() {
        addProductPage.enterProductName("Negative Price Bug Test " + System.currentTimeMillis());
        addProductPage.openPricingTab();
        addProductPage.enterRetailPrice("-500");
        addProductPage.clickSave();

        Assert.assertFalse(addProductPage.isProductSavedSuccessfully(),
                "KNOWN APPLICATION BUG: a negative Retail Price was accepted and saved without any validation error.");
    }

    // ===================== STOCK LEVEL =====================

    @DataProvider(name = "validStockScenarios")
    public Object[][] validStockScenarios() {
        return new Object[][]{
                {"TC_ZeroStock", "0"},
                {"TC_LargeStock", "99999"},
        };
    }

    @Test(dataProvider = "validStockScenarios", priority = 6)
    public void testAddProductWithValidStockLevel(String testCaseId, String stockLevel) {
        addProductPage.enterProductName("Stock Test " + testCaseId + " " + System.currentTimeMillis());
        addProductPage.enterStockLevel(stockLevel);
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                testCaseId + ": expected the product to save successfully with stock level " + stockLevel + ".");
    }

    /**
     * KNOWN APPLICATION BUG: the Stock Level field accepts a negative
     * value (e.g. -25) and saves the product with no validation error -
     * confirmed live, the product list then shows a stock of "-25".
     * Expected: the form should reject a negative stock level.
     * Actual: the product is saved with the negative stock stored as-is.
     */
    @Test(priority = 6)
    public void testAddProductWithNegativeStockLevelShouldBeRejected() {
        addProductPage.enterProductName("Negative Stock Bug Test " + System.currentTimeMillis());
        addProductPage.enterStockLevel("-25");
        addProductPage.clickSave();

        Assert.assertFalse(addProductPage.isProductSavedSuccessfully(),
                "KNOWN APPLICATION BUG: a negative Stock Level was accepted and saved without any validation error.");
    }

    // ===================== DUPLICATE PRODUCT CODE =====================

    /**
     * KNOWN APPLICATION BUG: saving a second product with a Product Code
     * that another product already uses succeeds silently - confirmed
     * live by creating two different products both coded "DUPCODE123".
     * Expected: the form should warn that the product code is already in use.
     * Actual: both products are saved with the identical code and no warning.
     */
    @Test(priority = 7)
    public void testDuplicateProductCodeShouldBeRejected() {
        String duplicateCode = "DUPCODE" + System.currentTimeMillis();

        addProductPage.enterProductName("Duplicate Code Product A " + System.currentTimeMillis());
        addProductPage.enterProductCode(duplicateCode);
        addProductPage.clickSave();
        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(), "Setup: first product should save.");

        addProductPage.navigateToAddProductPage();
        addProductPage.enterProductName("Duplicate Code Product B " + System.currentTimeMillis());
        addProductPage.enterProductCode(duplicateCode);
        addProductPage.clickSave();

        Assert.assertFalse(addProductPage.isProductSavedSuccessfully(),
                "KNOWN APPLICATION BUG: a second product was saved using a Product Code that was already in use, "
                        + "with no duplicate-code warning shown.");
    }

    // ===================== DESCRIPTION / SEO / CATEGORIES TABS =====================

    @Test(priority = 8)
    public void testAddProductWithDescriptionAndShortDescription() {
        addProductPage.enterProductName("Description Test " + System.currentTimeMillis());
        addProductPage.openDescriptionTab();
        addProductPage.enterDescription("Full description entered through CKEditor.");
        addProductPage.enterShortDescription("Short description entered through CKEditor.");
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with Description and Short Description filled in.");
    }

    @Test(priority = 8)
    public void testAddProductWithSeoFields() {
        addProductPage.enterProductName("SEO Test " + System.currentTimeMillis());
        addProductPage.openSeoTab();
        addProductPage.enterSeoMetaTitle("SEO Meta Title Test");
        addProductPage.enterSeoUrlPath("seo-url-path-test-" + System.currentTimeMillis());
        addProductPage.enterSeoMetaDescription("SEO meta description for the automation test product.");
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with SEO fields filled in.");
    }

    @Test(priority = 8)
    public void testAddProductWithCategoryAssigned() {
        addProductPage.enterProductName("Category Test " + System.currentTimeMillis());
        addProductPage.openCategoriesTab();
        addProductPage.selectFirstCategory();
        addProductPage.clickSave();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully with a category assigned.");
    }

    // ===================== SAVE & RELOAD =====================

    @Test(priority = 9)
    public void testSaveAndReloadKeepsAdminOnTheSameProduct() {
        String productName = "Save And Reload Test " + System.currentTimeMillis();
        addProductPage.enterProductName(productName);
        addProductPage.clickSaveAndReload();

        Assert.assertTrue(addProductPage.isProductSavedSuccessfully(),
                "Product should save successfully via Save & Reload.");
        Assert.assertTrue(addProductPage.getCurrentUrl().contains("action=edit"),
                "Save & Reload should return to the Edit page for the product just saved, not the product list.");
        Assert.assertEquals(addProductPage.getProductNameValue(), productName,
                "Save & Reload should keep the entered Product Name visible on the reloaded page.");
    }
}
